from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("explore/", views.explore, name="explore"),
    path("gems/", views.gems, name="gems"),
    path("compare/", views.compare, name="compare"),
    path("rising/", views.rising, name="rising"),
    path("awesome/", views.awesome_index, name="awesome_index"),
    path("awesome/<str:owner>/<str:name>/", views.awesome_detail, name="awesome_detail"),
    path("awesome/<str:owner>/<str:name>/refresh/", views.awesome_refresh, name="awesome_refresh"),
    path("trends/", views.trends, name="trends"),
    path("trends/refresh/", views.trends_refresh, name="trends_refresh"),
    path("feed/", views.feed, name="feed"),
    path("hot/", views.hot, name="hot"),
    path("og/<str:owner>/<str:name>.png", views.og_image, name="og_image"),
    path("share/", views.share_index, name="share_index"),
    path("share/create/", views.share_create, name="share_create"),
    path("share/<str:token>/", views.shared_list, name="shared_list"),
    path("share/<str:token>/delete/", views.share_delete, name="share_delete"),
    path("settings/", views.settings_page, name="settings"),
    path("profile/", views.profile, name="profile"),
    path("io/", views.import_export, name="import_export"),
    path("io/export.json", views.export_json, name="export_json"),
    path("io/export.md", views.export_markdown, name="export_markdown"),
    path("io/import/", views.import_bookmarks, name="import_bookmarks"),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
    path("bookmark/<int:repo_id>/toggle/", views.toggle_bookmark, name="toggle_bookmark"),
    path("bookmark/<int:repo_id>/delete/", views.delete_bookmark, name="delete_bookmark"),
    path("bookmark/<int:repo_id>/update/", views.update_bookmark, name="update_bookmark"),
    path("repo/<str:owner>/<str:name>/", views.repo_detail, name="repo_detail"),
]
