# Generated by Django 5.2.14 on 2026-05-20 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("owner_login", models.CharField(max_length=255)),
                ("owner_avatar", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("html_url", models.URLField()),
                ("language", models.CharField(blank=True, max_length=100)),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("watchers", models.IntegerField(default=0)),
                ("open_issues", models.IntegerField(default=0)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("homepage", models.URLField(blank=True)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at_github", models.DateTimeField(blank=True, null=True)),
                ("cached_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-stars"],
                "indexes": [
                    models.Index(
                        fields=["language"], name="discovery_r_languag_61b414_idx"
                    ),
                    models.Index(fields=["stars"], name="discovery_r_stars_229fa5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark",
                        to="discovery.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
