# Generated by Django 5.2.14 on 2026-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="ai_summary_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
