# Generated by Django 5.2.14 on 2026-05-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0002_repository_ai_summary_repository_ai_summary_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="ai_summary",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="ai_summary_at",
        ),
    ]
