# Generated by Django 5.2.14 on 2026-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0003_remove_repository_ai_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
