# Generated by Django 5.2.14 on 2026-05-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0006_create_cache_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwesomeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sections", models.JSONField(blank=True, default=list)),
                ("items_count", models.IntegerField(default=0)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="TopicTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100, unique=True)),
                ("this_month_count", models.IntegerField(default=0)),
                ("last_month_count", models.IntegerField(default=0)),
                ("growth_pct", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-growth_pct"],
            },
        ),
        migrations.CreateModel(
            name="StarSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.IntegerField()),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="discovery.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["repository", "captured_at"],
                        name="discovery_s_reposit_d0e41d_idx",
                    )
                ],
            },
        ),
    ]
