# Generated by Django 5.2.14 on 2026-05-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0007_awesomelist_topictrend_starsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="readme_summary",
            field=models.TextField(blank=True),
        ),
    ]
