# Generated by Django 5.2.14 on 2026-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0008_repository_readme_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=32, unique=True)),
                ("tag", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
