# Generated by Django 5.2.14 on 2026-05-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0009_sharedlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="kind",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["kind"], name="discovery_r_kind_e1013c_idx"),
        ),
    ]
